Repository rmagick/rmagick, pull requests merged in 2019-02, with the labels that each got.

#322 CI: add CircleCI config
  .circleci/config.yml
  rmagick.gemspec
Labels: on-hold

#344 Disable monitor feature on Windows
  ext/RMagick/rmimage.c
  ext/RMagick/rminfo.c
  ext/RMagick/rmutil.c
Labels: Windows

#329 Add AppVeyor configuration
  .appveyor.yml
Labels: CI, Windows

#341 CI: set strict options for setup script
  before_install_linux.sh
Labels: CI

#338 CI: remove latest IM from before_install_linux.sh
  before_install_linux.sh
Labels: CI

#333 Remove bundler version from setup script
  before_install_linux.sh
Labels: CI
